blank_issues_enabled: false

contact_links:
  - name: ğŸ“š MMSelfSup Documentation (å®˜æ–¹æ–‡æ¡£)
    url: https://mmselfsup.readthedocs.io/en/1.x/
    about: Check if your question is answered in docs
  - name: ğŸ’¬ Forum (å¯»æ±‚å¸®åŠ©)
    url: https://github.com/open-mmlab/mmselfsup/discussions
    about: Ask general usage questions and discuss with other MMSelfSup community members
  - name: ğŸŒ Explore OpenMMLab (å®˜ç½‘)
    url: https://openmmlab.com/
    about: Get know more about OpenMMLab
